version: '3.8'

services:
  neo4j:
    image: neo4j:5.15-community
    container_name: c2s-neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      # Authentication
      NEO4J_AUTH: neo4j/password123

      # Database configuration
      NEO4J_dbms_default__database: neo4j
      NEO4J_dbms_allow__upgrade: "true"

      # Memory configuration
      NEO4J_dbms_memory_heap_initial__size: 512m
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_memory_pagecache_size: 1G

      # Network configuration
      NEO4J_dbms_default__listen__address: 0.0.0.0
      NEO4J_dbms_connector_bolt_listen__address: 0.0.0.0:7687
      NEO4J_dbms_connector_http_listen__address: 0.0.0.0:7474

      # Enable APOC procedures
      NEO4J_PLUGINS: '["apoc"]'

      # Security settings
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*

    volumes:
      # Persist data
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7474/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

networks:
  default:
    name: c2s-network
